FROM mcr.microsoft.com/devcontainers/universal:3

RUN mkdir -p /usr/local/bin && \
    sudo curl -L https://github.com/biomejs/biome/releases/download/@biomejs/biome@2.1.3/biome-linux-x64 -o /usr/local/bin/biome && \
    sudo chmod +x /usr/local/bin/biome
